"""Semantic Robot SDK 公共接口；不包含任何具体 Robot 或 Runtime 实现。"""

from .backend import RobotBackend
from .config import CONFIG_ENV, RobotConfig, RobotDeployment, load_robot_deployment
from .fake_backend import FakeBackend, FakeBackendSnapshot, FakeGraspFixture
from .shared_fake_backend import SharedFakeBackend, SQLiteFakeStateStore
from .errors import (
    BackendRequestError,
    BackendUnavailable,
    ConfigurationError,
    DependencyUnavailable,
    GenerationMismatch,
    PlanningError,
    RobotSDKError,
)
from .models import (
    BaseTrajectoryPoint,
    Command,
    CommandState,
    EnvironmentCollisionObject,
    EnvironmentCollisionSet,
    Feedback,
    GripperTarget,
    JointLimit,
    JointTrajectoryPoint,
    MotionPlan,
    PlanKind,
    Pose,
    Result,
    RobotCapabilities,
    RobotState,
    SensorFrame,
    SceneObject,
    SceneRegion,
    SceneSnapshot,
    ToolDescriptor,
    ToolState,
)
from .providers import KinematicsProvider, MotionProvider, NavigationProvider
from .sensors import RobotStateSubscription, SensorSubscription

__all__ = [
    "BackendRequestError",
    "BackendUnavailable",
    "BaseTrajectoryPoint",
    "Command",
    "CommandState",
    "CONFIG_ENV",
    "ConfigurationError",
    "DependencyUnavailable",
    "EnvironmentCollisionObject",
    "FakeBackend",
    "FakeBackendSnapshot",
    "FakeGraspFixture",
    "EnvironmentCollisionSet",
    "Feedback",
    "GenerationMismatch",
    "GripperTarget",
    "JointLimit",
    "JointTrajectoryPoint",
    "KinematicsProvider",
    "MotionPlan",
    "MotionProvider",
    "NavigationProvider",
    "PlanKind",
    "PlanningError",
    "Pose",
    "Result",
    "RobotBackend",
    "RobotCapabilities",
    "RobotConfig",
    "RobotDeployment",
    "RobotSDKError",
    "RobotState",
    "RobotStateSubscription",
    "SensorFrame",
    "SceneObject",
    "SceneRegion",
    "SceneSnapshot",
    "SensorSubscription",
    "ToolDescriptor",
    "ToolState",
    "SharedFakeBackend",
    "SQLiteFakeStateStore",
    "load_robot_deployment",
]
